# Настройки pre-commit для проверки кода перед коммитом
repos:
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        args: ["--line-length", "88"]
        name: "Black formatter (line length 88)"

  - repo: https://gitlab.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--max-line-length", "88", "--ignore=E203,W503"]
        name: "Flake8 linter (ignores line breaks)"

  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.11
        name: "Black (Python 3.11 compatible)"

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "Import sorter"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        additional_dependencies: ["toml", "pygments"]
        exclude: "config.toml"

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.39.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
